def reverse_complement(s):
    #complement the strand, replaceing A with t, T with a, C with g and G with c
    s = s.replace('A', 't').replace('G', 'c').replace('T', 'a').replace('C', 'g')
    s =s.upper() 
    #reverse the strand
    s = s[::-1]

    return s

dna_string = '''GAATCTGCTGAGTATGCAGTGACATTGGTCTCTCTTCGGTCGTGGGTCGCTCTGGAGTTCGACCACAATGAACCGCTGGGCCTGGGAGCCACCATCTCGATTACAGCGTCTAAGGG
ATGACGGATGCCGTCTACAAGATCGGTACTTTACGTCTAATTTACTTGAATCAGTGGGCAACGATCTAACGTACGACGTTACCACCCGTGGTGCAGGTTATTAGCAGGGAATTGAAGACTGTAGTAGGTGCA
TACAGGGATGCTCCGTATCCGGGTTTGCTTAGCAATACTAATGTGAGCCACATCGAGGTGTGGTGAACTGTGATAATTTGGCCCACGACGTCCGTTTTTCGGCCCGTGTATCCCCATCGGTATTCGATTCTC
TGCGGGAGACGTGTTGAGACGGCGGAGAACCGGATCCGGTGAGAGACAGACCCTGAGGGATCGTATGAGCATCTCTCCTTATATTTCTGCAGTTTGGCGCCACCGGTTGATGAACAGCGCAGTTTAACTATC
CATCTATAGAGTTCCCGTAATGATGACCAAGTTTCCCACACAGCACAATTTTGTCTCGCCTCCCCTTAAATTACACTTTTTTCATGGCAGAACTGCCTCTCAGGGAGTTTACGGTGTTGAGGTCTCATGGGC
ACAGTTAAGTTCGTTATACCGATTCCCATTCAGCAGATTATACACAGCTCCTGATTCTAGCCCGCTGCCAAGGCTTTCCCACGTGGTACCGTGTTAATGTGATGTCGATGAGCAAAAACAATCCCATGCTCTT
CTCGAGGACTCAGTAGTGTTTCGAGGCTGATTTGAACACCGTCGCTATGAGATGGACGATGGATTGTGCGCTCCG'''
reverse_complement_dna = reverse_complement(dna_string)
print(reverse_complement_dna)
